# Generated by Django 3.1.3 on 2020-12-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_verify', '0004_auto_20201205_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsverification',
            name='user',
        ),
    ]
