# Generated by Django 3.1.3 on 2020-12-06 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('address_line_1', models.CharField(max_length=500)),
                ('address_line_2', models.CharField(blank=True, max_length=500)),
                ('zip_code', models.CharField(default=1, max_length=20)),
                ('building_details', models.CharField(max_length=500)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.profile')),
            ],
        ),
    ]
