# Generated by Django 3.1.3 on 2020-12-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20201207_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
