# Generated by Django 3.1.3 on 2020-11-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='Shop/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
