# Generated by Django 3.1.3 on 2020-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.TextField(),
        ),
    ]
