# Generated by Django 3.1.3 on 2020-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_ordertracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
