# Generated by Django 3.1.3 on 2020-11-23 14:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=jsonfield.fields.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='main_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
