# Generated by Django 3.1.3 on 2020-11-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_auto_20201123_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_four',
            field=models.ImageField(default=None, upload_to='Shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_three',
            field=models.ImageField(default=None, upload_to='Shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(default=None, upload_to='Shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='Shop/images'),
        ),
    ]
