# Generated by Django 3.1.3 on 2020-11-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_banner',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(default=None),
        ),
    ]
