# Generated by Django 3.1.3 on 2020-11-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_auto_20201123_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_banner',
        ),
    ]
