# Generated by Django 3.1.3 on 2020-11-26 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
