# Generated by Django 3.1.3 on 2020-12-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_wishlist_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Amazon', max_length=200),
        ),
    ]
